### ISSUE TITLE
PDF Parser - v1

### ISSUE THREAD

**Issue by ChakshuGautam** [ChatWithPDF/ai-tools#19]

**Comment by Gautam-Rajeev** [comment]
Ouput should look like this -  https://docs.google.com/spreadsheets/d/1q-aWJFUAlFHr_yNOwv5XNPgbg-Ghk7DuBiKdYm05MV4/edit?usp=sharing

**Comment by Gautam-Rajeev** [comment]
This is a duplicate. Covered [here](https://github.com/ChatWithPDF/ai-tools/issues/3)
