### ISSUE TITLE
Update PDF Parser to be used

### ISSUE THREAD

**Issue by ChakshuGautam** [ChatWithPDF/ai-tools#3]
- [ ] Store
  - [ ] Structure: Parent <> Child relationship
  - [ ] Images
  - [ ] Tables
  - [ ] Summary of chunks

- [ ] Search for the following fields
  - [ ] Fuzzy Search on everything text - list with a bunch of rows (relevancy score)
  - [ ] Vector Em Search - list with a bunch of rows (relevancy score)
  - [ ] Images - Start with child
  - [ ] Tables - Start with child

- [ ] Retrieval
  - [ ] parents wherever needed (figure out how to define need)

**Comment by Gautam-Rajeev** [comment]
@ksgr5566. The pdf parser work will be tracked here

**Comment by Gautam-Rajeev** [comment]
Ouput should look like this - [link](https://docs.google.com/spreadsheets/d/1q-aWJFUAlFHr_yNOwv5XNPgbg-Ghk7DuBiKdYm05MV4/edit?usp=sharing) @ksgr5566

**Comment by ChakshuGautam** [comment]
@GautamR-Samagra  to have hardcoded rules to figure out the relative hierarchy of chunks.

**Comment by Gautam-Rajeev** [comment]
Created csv :  [here](https://drive.google.com/file/d/1ALD2FkUl429b-Q56r1BVTz_4E2dwWEYv/view?usp=drive_link)

Required columns : 

ID | Doc ID | contentString | summaryString | summaryEmbedding | text | textEmbedding | page | Tags | semanticVersion(section index) | sectionTitle | sectionString | sectionImages | isTable | isImage | isQuoted | parentString | imageBase64 | titleOfCurrentSection | siblingChunkUp | siblingChunkDown | meta | linkedChunks




The csv above for Samagra docs  cover all except : 
isQuoted
Sibling Chunk up 
Sibling Chunk down
linked chunks 


@prtkjakhar @aashutosh-samagra use the csv as it also contains the image base64 which doesnt fit on the google sheet
